# Generated by Django 5.1.7 on 2025-04-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('pri', 'primary'), ('sec', 'secondary'), ('suc', 'success'), ('dan', 'danger'), ('war', 'warning'), ('inf', 'info'), ('lig', 'light'), ('dar', 'dark')], default='pri', max_length=3),
        ),
    ]
